// <auto-generated />
namespace DMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dms_v10_OrderType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dms_v10_OrderType));
        
        string IMigrationMetadata.Id
        {
            get { return "201905211234440_dms_v1.0_OrderType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
