// <auto-generated />
namespace DMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DMSDB_v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DMSDB_v10));
        
        string IMigrationMetadata.Id
        {
            get { return "201906060636487_DMSDB_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
