// <auto-generated />
namespace DMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dms_v10_DriverCreatedBy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dms_v10_DriverCreatedBy));
        
        string IMigrationMetadata.Id
        {
            get { return "201905310902126_dms_v1.0_DriverCreatedBy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
