//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.DomainObjects.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMS.DomainObjects.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some exception occured in database.
        /// </summary>
        public static string DataBaseException {
            get {
                return ResourceManager.GetString("DataBaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver activated successfully.
        /// </summary>
        public static string DriverActivated {
            get {
                return ResourceManager.GetString("DriverActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver deactivated successfully.
        /// </summary>
        public static string DriverDeactivated {
            get {
                return ResourceManager.GetString("DriverDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver deleted successfully.
        /// </summary>
        public static string DriverDeleted {
            get {
                return ResourceManager.GetString("DriverDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver No. already exists.
        /// </summary>
        public static string DriverNoExisted {
            get {
                return ResourceManager.GetString("DriverNoExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver(s) created successfully.
        /// </summary>
        public static string DriversCreated {
            get {
                return ResourceManager.GetString("DriversCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver(s) updated successfully.
        /// </summary>
        public static string DriversUpdated {
            get {
                return ResourceManager.GetString("DriversUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License number already exists.
        /// </summary>
        public static string DrivingLicenseNoExisted {
            get {
                return ResourceManager.GetString("DrivingLicenseNoExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expeditor Email.
        /// </summary>
        public static string ExpeditorEmailCheck {
            get {
                return ResourceManager.GetString("ExpeditorEmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while uploading the file.
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GateIn created successfully.
        /// </summary>
        public static string GateInCreated {
            get {
                return ResourceManager.GetString("GateInCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GateOut created successfully.
        /// </summary>
        public static string GateOutCreated {
            get {
                return ResourceManager.GetString("GateOutCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity number already exists.
        /// </summary>
        public static string IdentityNoExisted {
            get {
                return ResourceManager.GetString("IdentityNoExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Old Password.
        /// </summary>
        public static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid address.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application ID.
        /// </summary>
        public static string InvalidApplication {
            get {
                return ResourceManager.GetString("InvalidApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid city.
        /// </summary>
        public static string InvalidCityID {
            get {
                return ResourceManager.GetString("InvalidCityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid confirm password.
        /// </summary>
        public static string InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Confirm Password.
        /// </summary>
        public static string InvalidConfirmUserPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Driver.
        /// </summary>
        public static string InvalidDriver {
            get {
                return ResourceManager.GetString("InvalidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid driver number.
        /// </summary>
        public static string InvalidDriverNo {
            get {
                return ResourceManager.GetString("InvalidDriverNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid driving license image.
        /// </summary>
        public static string InvalidDrivingLicenseImage {
            get {
                return ResourceManager.GetString("InvalidDrivingLicenseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid driving license number.
        /// </summary>
        public static string InvalidDrivingLicenseNo {
            get {
                return ResourceManager.GetString("InvalidDrivingLicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expeditor Email.
        /// </summary>
        public static string InvalidExpeditorEmail {
            get {
                return ResourceManager.GetString("InvalidExpeditorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expeditor Name.
        /// </summary>
        public static string InvalidExpeditorName {
            get {
                return ResourceManager.GetString("InvalidExpeditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expeditor name should be 3-15 characters.
        /// </summary>
        public static string InvalidExpeditorNameLength {
            get {
                return ResourceManager.GetString("InvalidExpeditorNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expeditor TypeID.
        /// </summary>
        public static string InvalidExpeditorTypeID {
            get {
                return ResourceManager.GetString("InvalidExpeditorTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid expiry date.
        /// </summary>
        public static string InvalidExpireDate {
            get {
                return ResourceManager.GetString("InvalidExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only JPEG and PNG are supported.
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid identity image.
        /// </summary>
        public static string InvalidIdentityImage {
            get {
                return ResourceManager.GetString("InvalidIdentityImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid identity number.
        /// </summary>
        public static string InvalidIdentityNo {
            get {
                return ResourceManager.GetString("InvalidIdentityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid image.
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid KIR number.
        /// </summary>
        public static string InvalidKIRNo {
            get {
                return ResourceManager.GetString("InvalidKIRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIR No should be 3-25 characters.
        /// </summary>
        public static string InvalidKIRNoLength {
            get {
                return ResourceManager.GetString("InvalidKIRNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid max dimension.
        /// </summary>
        public static string InvalidMaxDimension {
            get {
                return ResourceManager.GetString("InvalidMaxDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension should be 3-12 characters.
        /// </summary>
        public static string InvalidMaxDimensionLength {
            get {
                return ResourceManager.GetString("InvalidMaxDimensionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid max weight.
        /// </summary>
        public static string InvalidMaxWeight {
            get {
                return ResourceManager.GetString("InvalidMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Menu Code.
        /// </summary>
        public static string InvalidMenuCode {
            get {
                return ResourceManager.GetString("InvalidMenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner address should be 3-50 characters .
        /// </summary>
        public static string InvalidPartnerAddressLength {
            get {
                return ResourceManager.GetString("InvalidPartnerAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner initial should be 3-15 characters.
        /// </summary>
        public static string InvalidPartnerInitialLength {
            get {
                return ResourceManager.GetString("InvalidPartnerInitialLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid phone.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIC ID.
        /// </summary>
        public static string InvalidPICID {
            get {
                return ResourceManager.GetString("InvalidPICID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid plate number.
        /// </summary>
        public static string InvalidPlateNumber {
            get {
                return ResourceManager.GetString("InvalidPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate number  should be 3-12 characters.
        /// </summary>
        public static string InvalidPlateNumberLength {
            get {
                return ResourceManager.GetString("InvalidPlateNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid police number.
        /// </summary>
        public static string InvalidPoliceNo {
            get {
                return ResourceManager.GetString("InvalidPoliceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police number  should be 3-12 characters.
        /// </summary>
        public static string InvalidPoliceNoLength {
            get {
                return ResourceManager.GetString("InvalidPoliceNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pool.
        /// </summary>
        public static string InvalidPool {
            get {
                return ResourceManager.GetString("InvalidPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid pool code.
        /// </summary>
        public static string InvalidPoolCode {
            get {
                return ResourceManager.GetString("InvalidPoolCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid pool.
        /// </summary>
        public static string InvalidPoolID {
            get {
                return ResourceManager.GetString("InvalidPoolID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid pool name.
        /// </summary>
        public static string InvalidPoolName {
            get {
                return ResourceManager.GetString("InvalidPoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Postalcode ID.
        /// </summary>
        public static string InvalidPostalCodeID {
            get {
                return ResourceManager.GetString("InvalidPostalCodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid Region.
        /// </summary>
        public static string InvalidRegion {
            get {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid Role.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Role Code.
        /// </summary>
        public static string InvalidRoleCode {
            get {
                return ResourceManager.GetString("InvalidRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid shipper.
        /// </summary>
        public static string InvalidShipperID {
            get {
                return ResourceManager.GetString("InvalidShipperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid User.
        /// </summary>
        public static string InvalidUserID {
            get {
                return ResourceManager.GetString("InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Password.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Vehicle.
        /// </summary>
        public static string InvalidVehicle {
            get {
                return ResourceManager.GetString("InvalidVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid vehicle type.
        /// </summary>
        public static string InvalidVehicleTypeID {
            get {
                return ResourceManager.GetString("InvalidVehicleTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide valid vehicle type name.
        /// </summary>
        public static string InvalidVehicleTypeName {
            get {
                return ResourceManager.GetString("InvalidVehicleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Failed.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logged In Successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Activity Retrived.
        /// </summary>
        public static string MenuActivityRetrived {
            get {
                return ResourceManager.GetString("MenuActivityRetrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be same as old password.
        /// </summary>
        public static string NewPasswordMustbeDifferent {
            get {
                return ResourceManager.GetString("NewPasswordMustbeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record(s) found.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Successfully in TMS.
        /// </summary>
        public static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order(s) created successfully in TMS.
        /// </summary>
        public static string OrdersCreated {
            get {
                return ResourceManager.GetString("OrdersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order(s) updated successfully in TMS.
        /// </summary>
        public static string OrdersUpdated {
            get {
                return ResourceManager.GetString("OrdersUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Updated Successfully in TMS.
        /// </summary>
        public static string OrderUpdated {
            get {
                return ResourceManager.GetString("OrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner(s) created successfully.
        /// </summary>
        public static string PartnerCreated {
            get {
                return ResourceManager.GetString("PartnerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner number already exists.
        /// </summary>
        public static string PartnerNoExisted {
            get {
                return ResourceManager.GetString("PartnerNoExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner(s) updated successfully.
        /// </summary>
        public static string PartnerUpdated {
            get {
                return ResourceManager.GetString("PartnerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and contain one upper case, one lower case, one number and special character.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password must be same.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC(s) created successfully.
        /// </summary>
        public static string PicCreated {
            get {
                return ResourceManager.GetString("PicCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC deleted successfully.
        /// </summary>
        public static string PicDeleted {
            get {
                return ResourceManager.GetString("PicDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC(s) updated successfully.
        /// </summary>
        public static string PicUpdated {
            get {
                return ResourceManager.GetString("PicUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool activated successfully.
        /// </summary>
        public static string PoolActivated {
            get {
                return ResourceManager.GetString("PoolActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool deactivated successfully.
        /// </summary>
        public static string PoolDeactivated {
            get {
                return ResourceManager.GetString("PoolDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool deleted successfully.
        /// </summary>
        public static string PoolDeleted {
            get {
                return ResourceManager.GetString("PoolDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool(s) created successfully.
        /// </summary>
        public static string PoolsCreated {
            get {
                return ResourceManager.GetString("PoolsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool(s) updated successfully.
        /// </summary>
        public static string PoolsUpdated {
            get {
                return ResourceManager.GetString("PoolsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role yang dipilih sudah di assign ke username tertentu.
        /// </summary>
        public static string RoleCannontBeDeleted {
            get {
                return ResourceManager.GetString("RoleCannontBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role code already exists.
        /// </summary>
        public static string RoleCodeExists {
            get {
                return ResourceManager.GetString("RoleCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) created successfully.
        /// </summary>
        public static string RolesCreated {
            get {
                return ResourceManager.GetString("RolesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) deleted successfully.
        /// </summary>
        public static string RolesDeleted {
            get {
                return ResourceManager.GetString("RolesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) updated successfully.
        /// </summary>
        public static string RolesUpdated {
            get {
                return ResourceManager.GetString("RolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transporter Id.
        /// </summary>
        public static string TransporterId {
            get {
                return ResourceManager.GetString("TransporterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip assigned successfully.
        /// </summary>
        public static string TripAssigned {
            get {
                return ResourceManager.GetString("TripAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is In-Active.
        /// </summary>
        public static string UserInActive {
            get {
                return ResourceManager.GetString("UserInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists.
        /// </summary>
        public static string UserNameExisted {
            get {
                return ResourceManager.GetString("UserNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already assigned with this role and region.
        /// </summary>
        public static string UserRoleAlreadyAssigned {
            get {
                return ResourceManager.GetString("UserRoleAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) created successfully.
        /// </summary>
        public static string UserRoleCreated {
            get {
                return ResourceManager.GetString("UserRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) deleted successfully.
        /// </summary>
        public static string UserRoleDeleted {
            get {
                return ResourceManager.GetString("UserRoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) updated successfully.
        /// </summary>
        public static string UserRoleUpdated {
            get {
                return ResourceManager.GetString("UserRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) created successfully.
        /// </summary>
        public static string UsersCreated {
            get {
                return ResourceManager.GetString("UsersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) deleted successfully.
        /// </summary>
        public static string UsersDeleted {
            get {
                return ResourceManager.GetString("UsersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) updated successfully.
        /// </summary>
        public static string UsersUpdated {
            get {
                return ResourceManager.GetString("UsersUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) Profile updated successfully in TMS.
        /// </summary>
        public static string UsersUpdateProfile {
            get {
                return ResourceManager.GetString("UsersUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle activated successfully.
        /// </summary>
        public static string VehicleActivated {
            get {
                return ResourceManager.GetString("VehicleActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle(s) created successfully.
        /// </summary>
        public static string VehicleCreated {
            get {
                return ResourceManager.GetString("VehicleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle deactivated successfully.
        /// </summary>
        public static string VehicleDeactivated {
            get {
                return ResourceManager.GetString("VehicleDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle deleted successfully.
        /// </summary>
        public static string VehicleDeleted {
            get {
                return ResourceManager.GetString("VehicleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle(s) updated successfully.
        /// </summary>
        public static string VehicleUpdated {
            get {
                return ResourceManager.GetString("VehicleUpdated", resourceCulture);
            }
        }
    }
}
