// <auto-generated />
namespace OMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class oms_v10_Business : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oms_v10_Business));
        
        string IMigrationMetadata.Id
        {
            get { return "201905161011110_oms_v1.0_Business"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
