// <auto-generated />
namespace OMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OMS_v10_AllInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OMS_v10_AllInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201904260626019_OMS_v1.0_AllInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
