// <auto-generated />
namespace TMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tms_v10_SOPONumberAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tms_v10_SOPONumberAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201906030739030_tms_v1.0_SOPONumberAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
