// <auto-generated />
namespace TMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tmsv10_Unusedtablecleaned : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tmsv10_Unusedtablecleaned));
        
        string IMigrationMetadata.Id
        {
            get { return "201905300801073_tmsv1.0_Unusedtablecleaned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
