// <auto-generated />
namespace TMS.DataGateway.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201906070606514_DriverPartnerTypeIdAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201906070606514_DriverPartnerTypeIdAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201906071121007_201906070606514_DriverPartnerTypeIdAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
