//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DomainObjects.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMS.DomainObjects.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some exception occrued in database.
        /// </summary>
        public static string DataBaseException {
            get {
                return ResourceManager.GetString("DataBaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Application ID.
        /// </summary>
        public static string InvalidApplication {
            get {
                return ResourceManager.GetString("InvalidApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Confirm Password.
        /// </summary>
        public static string InvalidConfirmUserPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Menu Code.
        /// </summary>
        public static string InvalidMenuCode {
            get {
                return ResourceManager.GetString("InvalidMenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid Region.
        /// </summary>
        public static string InvalidRegion {
            get {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid Role.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Role Code.
        /// </summary>
        public static string InvalidRoleCode {
            get {
                return ResourceManager.GetString("InvalidRoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Valid User.
        /// </summary>
        public static string InvalidUserID {
            get {
                return ResourceManager.GetString("InvalidUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Password.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Failed.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Logged In Successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Activities Retrieved.
        /// </summary>
        public static string MenuActivityRetrieved {
            get {
                return ResourceManager.GetString("MenuActivityRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Orders.
        /// </summary>
        public static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record(s) found.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Successfully in OMS.
        /// </summary>
        public static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Downloaded.
        /// </summary>
        public static string OrdersDownloaded {
            get {
                return ResourceManager.GetString("OrdersDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status Retrieved.
        /// </summary>
        public static string OrderStatusRetrieved {
            get {
                return ResourceManager.GetString("OrderStatusRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order updated successfully .
        /// </summary>
        public static string OrderUpdated {
            get {
                return ResourceManager.GetString("OrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 8 characters and contain one upper case, one lower case, one number and special character.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password must be same.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role code alredy exist.
        /// </summary>
        public static string RoleCodeExists {
            get {
                return ResourceManager.GetString("RoleCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) created successfully.
        /// </summary>
        public static string RolesCreated {
            get {
                return ResourceManager.GetString("RolesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) deleted successfully.
        /// </summary>
        public static string RolesDeleted {
            get {
                return ResourceManager.GetString("RolesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s) updated successfully.
        /// </summary>
        public static string RolesUpdated {
            get {
                return ResourceManager.GetString("RolesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is In-Active.
        /// </summary>
        public static string UserInActive {
            get {
                return ResourceManager.GetString("UserInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name alredy exist.
        /// </summary>
        public static string UserNameExisted {
            get {
                return ResourceManager.GetString("UserNameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already assigned with this role and region.
        /// </summary>
        public static string UserRoleAlreadyAssigned {
            get {
                return ResourceManager.GetString("UserRoleAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) created successfully.
        /// </summary>
        public static string UserRoleCreated {
            get {
                return ResourceManager.GetString("UserRoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) deleted successfully.
        /// </summary>
        public static string UserRoleDeleted {
            get {
                return ResourceManager.GetString("UserRoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRole(s) updated successfully.
        /// </summary>
        public static string UserRoleUpdated {
            get {
                return ResourceManager.GetString("UserRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) created successfully.
        /// </summary>
        public static string UsersCreated {
            get {
                return ResourceManager.GetString("UsersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) deleted successfully.
        /// </summary>
        public static string UsersDeleted {
            get {
                return ResourceManager.GetString("UsersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) updated successfully.
        /// </summary>
        public static string UsersUpdated {
            get {
                return ResourceManager.GetString("UsersUpdated", resourceCulture);
            }
        }
    }
}
