using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TMS.DataGateway.DataModels
{
    [Table("FieldLabelMenu", Schema = "TMS")]
    public class FieldLabelMenu
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        public Menu Menu { get; set; }
        [MaxLength(30)]
        public string FieldLabel { get; set; }
        public int IsMandatory { get; set; }
        public int IsDisplayed { get; set; }
        public int IsReadOnly { get; set; }
        public string DefaultValue { get; set; }
        public int IsRunningNumber { get; set; }
        public int IsAutoGeneratedv { get; set; }
        public string FieldType { get; set; }
        public string TableSave { get; set; }
        public string FieldSave { get; set; }
        public string IncludeObject { get; set; }
        public string ExcludeObject { get; set; }
        public string LogicCode { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string CreatedBy
        {
            get { return "SYSTEM"; }
            set { }
        }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreatedTime
        {
            get { return DateTime.Now; }
            set { }
        }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
    }
}
